### ISSUE TITLE
ParmLearnDocs.txt, missing CC mode pull down menu options

### ISSUE THREAD

**Issue by michaelsjackson** [Ultraschall/ultraschall-and-reaper-docs#1]
Looks great, thanks for the efforts, however I could not find any settings for the CC mode pulldown menu entries:
-Absolute
-Relative 1..3
-Toggle

Especially Toggle is very important for certain mapping scenarios. This option gives ultimate freedom in mapping those cases.

When completed, I guess this will give lots of power to Reaper! Thanks very much again to you and Anton9!

Another side comment, somehow it should be possible getting from parameter name its index number, so the mappings could be done based on regex results. Then you could create a list of names and where to map to, not only for wet and bypass, cutoff/filter and resonance would be first candidate general use cases.

**Comment by mespotine** [comment]
> Looks great, thanks for the efforts, however I could not find any settings for the CC mode pulldown menu entries:
> -Absolute
> -Relative 1..3
> -Toggle
> 
> Especially Toggle is very important for certain mapping scenarios. This option gives ultimate freedom in mapping those cases.

You're right, If forgot to add them. Thanks for pointing that out :)

> Another side comment, somehow it should be possible getting from parameter name its index number, so the mappings could be done based on regex results. Then you could create a list of names and where to map to, not only for wet and bypass, cutoff/filter and resonance would be first candidate general use cases.

I'm not sure, what you mean by that. Do you mean, the documentation should be machine-readable, so you can use it's contents for your own functions?

**Comment by michaelsjackson** [comment]
No, as I do not know available API functions in general, I am not sure if this is possible already, but I would guess so, so this would allow any kind of free programming. In short we could build anything we want.

**Comment by mespotine** [comment]
Ok, I've added the information(forgot to tell you that :) )
